### ISSUE TITLE
dataset_split is not conform

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/cicd#3]
@mattbit Not all dataset has `validation` as `dataset_split`, I currently added this quick fix, to be automated.
https://github.com/Giskard-AI/cicd/blob/6e01c02b6f1551439a9638e75bf4d7d12c82b34b/scan_retrieved.py#L44

**Comment by Inokinoki** [comment]
We allow user to choose one (from cli or Giskard Evaluator) or use the first one
